version: "3.9"

services:
  django:
    image: parking-control:develop
    build:
      context: .
    environment:
      - ENVIRONMENT=production
      - SECRET_KEY=l889thd#01*f$$zs14xhpx#^s^!cfz9i08m@ub^^oa62%_cjs85
      - DEBUG=false
      - ALLOWED_HOSTS=*
    volumes:
      - data:/app/data
      - static_files:/app/static
  
  nginx:
    image: nginx:latest
    ports:
      - "8000:443"
    volumes:
      - .assets/nginx/nginx.default.conf:/etc/nginx/conf.d/default.conf
      - .assets/nginx/localhost.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - .assets/nginx/localhost.key:/etc/ssl/private/nginx-selfsigned.key
      - static_files:/home/app/web/staticfiles

volumes:
  data:
  static_files:
