name: cd-action

on:
  push:
    branches:
      - 'main'
      - 'release/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} 
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PWD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-publish:
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0      

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}            

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PWD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: DockerFile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
