# Generated by Django 4.1.3 on 2023-08-14 21:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parking_spot_number', models.CharField(max_length=10, unique=True)),
                ('license_plate_car', models.CharField(max_length=7)),
                ('brand_car', models.CharField(max_length=70)),
                ('model_car', models.CharField(max_length=70)),
                ('color_car', models.CharField(max_length=70)),
                ('registration_date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('apartment', models.CharField(max_length=30)),
                ('block', models.CharField(max_length=30)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['registration_date'],
            },
        ),
    ]
