# Generated by Django 4.1.3 on 2023-08-14 20:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parking_spot_number', models.CharField(max_length=10, unique=True)),
                ('license_plate_car', models.CharField(max_length=7)),
                ('brand_car', models.CharField(max_length=70)),
                ('model_car', models.CharField(max_length=70)),
                ('color_car', models.CharField(max_length=70)),
                ('registration_date', models.DateField()),
                ('responsible_name', models.CharField(max_length=30)),
                ('apartment', models.CharField(max_length=30)),
                ('block', models.CharField(max_length=30)),
            ],
        ),
    ]
